// src/components/createDishForm/constants/ingredientsData.ts

export interface IngredientOption {
  name_ua: string;
  name_en: string;
}

export const units = [
  "г",
  "мл",
  "шт",
  "ст.л.",
  "ч.л.",
  "пучок",
  "гілочка",
  "листок",
];

export const ingredientsByCategory: Record<string, IngredientOption[]> = {
  "М'ясо": [
    { name_ua: "Курятина", name_en: "Chicken" },
    { name_ua: "Яловичина", name_en: "Beef" },
    { name_ua: "Свинина", name_en: "Pork" },
    { name_ua: "Індичка", name_en: "Turkey" },
    { name_ua: "Телятина", name_en: "Veal" },
    { name_ua: "Фарш яловичий", name_en: "Ground beef" },
    { name_ua: "Фарш свинячий", name_en: "Ground pork" },
    { name_ua: "Фарш курячий", name_en: "Ground chicken" },
    { name_ua: "Фарш змішаний", name_en: "Mixed ground meat" },
    { name_ua: "Кролик", name_en: "Rabbit" },
    { name_ua: "Баранина", name_en: "Lamb" },
    { name_ua: "Качка", name_en: "Duck" },
    { name_ua: "Гуска", name_en: "Goose" },
    { name_ua: "Бекон", name_en: "Bacon" },
    { name_ua: "Шинка", name_en: "Ham" },
    { name_ua: "Сосиски", name_en: "Sausages" },
    { name_ua: "Ковбаса", name_en: "Salami" },
    { name_ua: "Печінка", name_en: "Liver" },
    { name_ua: "Серце", name_en: "Heart" },
    { name_ua: "Крильця курячі", name_en: "Chicken wings" },
    { name_ua: "Філе куряче", name_en: "Chicken fillet" },
    { name_ua: "Яйце", name_en: "Egg" }
  ],
  "Риба": [
    { name_ua: "Скумбрія", name_en: "Mackerel" },
    { name_ua: "Лосось", name_en: "Salmon" },
    { name_ua: "Тунець", name_en: "Tuna" },
    { name_ua: "Щука", name_en: "Pike" },
    { name_ua: "Оселедець", name_en: "Herring" },
    { name_ua: "Дорадо", name_en: "Dorado" },
    { name_ua: "Форель", name_en: "Trout" },
    { name_ua: "Минтай", name_en: "Pollock" },
    { name_ua: "Тріска", name_en: "Cod" },
    { name_ua: "Палтус", name_en: "Halibut" },
    { name_ua: "Камбала", name_en: "Flounder" },
    { name_ua: "Окунь", name_en: "Perch" },
    { name_ua: "Сом", name_en: "Catfish" },
  ],

  "Морепродукти": [
    { name_ua: "Креветки", name_en: "Shrimp" },
    { name_ua: "Кальмари", name_en: "Squid" },
    { name_ua: "Мідії", name_en: "Mussels" },
    { name_ua: "Восьминіг", name_en: "Octopus" },
    { name_ua: "Устриці", name_en: "Oysters" },
    { name_ua: "Раки", name_en: "Crayfish" },
    { name_ua: "Морський гребінець", name_en: "Scallop" },
    { name_ua: "Ікра", name_en: "Caviar" },
  ],
  "Крупи": [
    { name_ua: "Рис", name_en: "Rice" },
    { name_ua: "Гречка", name_en: "Buckwheat" },
    { name_ua: "Булгур", name_en: "Bulgur" },
    { name_ua: "Пшоно", name_en: "Millet" },
    { name_ua: "Кускус", name_en: "Couscous" },
    { name_ua: "Вівсянка", name_en: "Oatmeal" },
    { name_ua: "Кіноа", name_en: "Quinoa" },
    { name_ua: "Манка", name_en: "Semolina" },
    { name_ua: "Перлова крупа", name_en: "Pearl barley" },
    { name_ua: "Кукурудзяна крупа", name_en: "Corn grits" },
    { name_ua: "Ячна крупа", name_en: "Barley groats" },
    { name_ua: "Полба", name_en: "Spelt" },
    { name_ua: "Сочевиця", name_en: "Lentils" },
    { name_ua: "Нутова крупа", name_en: "Chickpea groats" },
    { name_ua: "Зелена гречка", name_en: "Green buckwheat" },
  ],
  "Овочі": [
    { name_ua: "Картопля", name_en: "Potato" },
    { name_ua: "Морква", name_en: "Carrot" },
    { name_ua: "Помідор", name_en: "Tomato" },
    { name_ua: "Огірок", name_en: "Cucumber" },
    { name_ua: "Цибуля", name_en: "Onion" },
    { name_ua: "Часник", name_en: "Garlic" },
    { name_ua: "Капуста", name_en: "Cabbage" },
    { name_ua: "Броколі", name_en: "Broccoli" },
    { name_ua: "Солодкий перець", name_en: "Bell pepper" },
    { name_ua: "Кабачок", name_en: "Zucchini" },
    { name_ua: "Гарбуз", name_en: "Pumpkin" },
    { name_ua: "Буряк", name_en: "Beet" },
    { name_ua: "Редис", name_en: "Radish" },
    { name_ua: "Кукурудза", name_en: "Corn" },
    { name_ua: "Баклажан", name_en: "Eggplant" },
    { name_ua: "Спаржа", name_en: "Asparagus" },
    { name_ua: "Шпинат", name_en: "Spinach" },
    { name_ua: "Щавель", name_en: "Sorrel" },
    { name_ua: "Листовий салат", name_en: "Lettuce" },
    { name_ua: "Перець чилі", name_en: "Chili pepper" },
    { name_ua: "Горох", name_en: "Peas" },
    { name_ua: "Квасоля", name_en: "Beans" },
    { name_ua: "Цвітна капуста", name_en: "Cauliflower" },
    { name_ua: "Гриби", name_en: "Mushrooms" },
    { name_ua: "Солодка картопля", name_en: "Sweet potato" },
  ],
  "Фрукти": [
    { name_ua: "Яблуко", name_en: "Apple" },
    { name_ua: "Банан", name_en: "Banana" },
    { name_ua: "Апельсин", name_en: "Orange" },
    { name_ua: "Лимон", name_en: "Lemon" },
    { name_ua: "Виноград", name_en: "Grapes" },
    { name_ua: "Мандарин", name_en: "Tangerine" },
    { name_ua: "Авокадо", name_en: "Avocado" },
    { name_ua: "Ківі", name_en: "Kiwi" },
    { name_ua: "Персик", name_en: "Peach" },
    { name_ua: "Абрикос", name_en: "Apricot" },
    { name_ua: "Диня", name_en: "Melon" },
    { name_ua: "Кавун", name_en: "Watermelon" },
    { name_ua: "Полуниця", name_en: "Strawberry" },
    { name_ua: "Малина", name_en: "Raspberry" },
    { name_ua: "Черешня", name_en: "Cherry" },
    { name_ua: "Слива", name_en: "Plum" },
    { name_ua: "Гранат", name_en: "Pomegranate" },
    { name_ua: "Ананас", name_en: "Pineapple" },
    { name_ua: "Манго", name_en: "Mango" },
    { name_ua: "Кокос", name_en: "Coconut" },
    { name_ua: "Лайм", name_en: "Lime" },
  ],
  "Молочка": [
    { name_ua: "Молоко", name_en: "Milk" },
    { name_ua: "Сир кисломолочний", name_en: "Cottage cheese" },
    { name_ua: "Сир", name_en: "Cheese" },
    { name_ua: "Сметана", name_en: "Sour cream" },
    { name_ua: "Йогурт", name_en: "Yogurt" },
    { name_ua: "Кефір", name_en: "Kefir" },
    { name_ua: "Вершкове масло", name_en: "Butter" },
    { name_ua: "Твердий сир", name_en: "Hard cheese" },
    { name_ua: "Моцарелла", name_en: "Mozzarella" },
    { name_ua: "Фета", name_en: "Feta" },
    { name_ua: "Пармезан", name_en: "Parmesan" },
    { name_ua: "Вершки", name_en: "Cream" },
    { name_ua: "Ряжанка", name_en: "Ryazhenka" },
    { name_ua: "Маскарпоне", name_en: "Mascarpone" },
    { name_ua: "Рікотта", name_en: "Ricotta" },
    { name_ua: "Бринза", name_en: "Brinza" },
    { name_ua: "Плавлений сир", name_en: "Processed cheese" },
  ],
  "Зелень": [
    { name_ua: "Петрушка", name_en: "Parsley" },
    { name_ua: "Кріп", name_en: "Dill" },
    { name_ua: "Кінза", name_en: "Cilantro" },
    { name_ua: "Базилік", name_en: "Basil" },
    { name_ua: "Зелена цибуля", name_en: "Green onion" },
    { name_ua: "Рукола", name_en: "Arugula" },
    { name_ua: "М'ята", name_en: "Mint" },
    { name_ua: "Розмарин", name_en: "Rosemary" },
    { name_ua: "Чебрець", name_en: "Thyme" },
    { name_ua: "Орегано", name_en: "Oregano" },
    { name_ua: "Лавровий лист", name_en: "Bay leaf" },
    { name_ua: "Шавлія", name_en: "Sage" },
  ],
  "Спеції": [
    { name_ua: "Сіль", name_en: "Salt" },
    { name_ua: "Перець чорний мелений", name_en: "Ground black pepper" },
    { name_ua: "Паприка", name_en: "Paprika" },
    { name_ua: "Куркума", name_en: "Turmeric" },
    { name_ua: "Кориця", name_en: "Cinnamon" },
    { name_ua: "Гвоздика", name_en: "Clove" },
    { name_ua: "Лавровий лист", name_en: "Bay leaf" },
    { name_ua: "Сушений часник", name_en: "Dried garlic" },
    { name_ua: "Імбир", name_en: "Ginger" },
    { name_ua: "Мускатний горіх", name_en: "Nutmeg" },
    { name_ua: "Кмин", name_en: "Cumin" },
    { name_ua: "Коріандр", name_en: "Coriander" },
    { name_ua: "Каррі", name_en: "Curry powder" },
    { name_ua: "Червоний перець", name_en: "Red pepper flakes" },
    { name_ua: "Сушений базилік", name_en: "Dried basil" },
    { name_ua: "Ванілін", name_en: "Vanillin" },
  ],

  "Інше": [    
    { name_ua: "Вода", name_en: "Water" },
    { name_ua: "Олія", name_en: "Oil" },
    { name_ua: "Цукор", name_en: "Sugar" },
    { name_ua: "Оцет", name_en: "Vinegar" },
    { name_ua: "Лимонний сік", name_en: "Lemon juice" },
    { name_ua: "Сода", name_en: "Baking soda" },
    { name_ua: "Соєвий соус", name_en: "Soy sauce" },
    { name_ua: "Майонез", name_en: "Mayonnaise" },
    { name_ua: "Томатна паста", name_en: "Tomato paste" },
    { name_ua: "Мед", name_en: "Honey" },
    { name_ua: "Гірчиця", name_en: "Mustard" },
    { name_ua: "Кетчуп", name_en: "Ketchup" },
    { name_ua: "Желатин", name_en: "Gelatin" },
    { name_ua: "Дріжджі", name_en: "Yeast" },
    { name_ua: "Вершковий сир", name_en: "Cream cheese" },
    { name_ua: "Оливкова олія", name_en: "Olive oil" },
  ],
};

export const mainCategories = [
  "М'ясо",
  "Риба",
  "Морепродукти",
  "Крупи",
  "Овочі",
  "Фрукти",
  "Молочка",
];

export const optionalCategories = ["Зелень", "Спеції", "Інше"];
